name: CI

on: [push]

jobs:
  inactive_accounts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Check inactive accounts
      run: node report-inactive-accounts.js
      env:
        consumer_key: ${{ secrets.consumer_key }}
        consumer_secret: ${{ secrets.consumer_secret }}
        access_token: ${{ secrets.access_token }}
        access_token_secret: ${{ secrets.access_token_secret }}
